// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolingExtractor.Infrastructure.Data;

#nullable disable

namespace ToolingExtractor.Infrastructure.Migrations
{
    [DbContext(typeof(ToolingDbContext))]
    [Migration("20260605072046_AddToolListNumber")]
    partial class AddToolListNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ToolingExtractor.Core.Models.ExtractionJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmendedFilesDetected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeringIpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeringWorkstation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExtractionJobs");
                });

            modelBuilder.Entity("ToolingExtractor.Core.Models.FileHighlightPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.HasIndex("SourceFileHash", "PageNumber")
                        .IsUnique();

                    b.ToTable("FileHighlightPages");
                });

            modelBuilder.Entity("ToolingExtractor.Core.Models.ToolingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmendmentEvidenceSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArborDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CamProgrammer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ConsumableToolDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtractionJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FluteLengthL1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PdfRowOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PdfType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawExtractedJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RevisionConflictDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCornerRadius")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolDiameterD1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolExtLengthL2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolHolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolListId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolListNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolPathTimeMinutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolRegisteredBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolSupplier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAmendmentDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Workcenter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionJobId");

                    b.HasIndex("Machine");

                    b.HasIndex("Operation");

                    b.HasIndex("PartNumber");

                    b.HasIndex("RevisionConflictDetected");

                    b.HasIndex("SourceFileHash");

                    b.HasIndex("ToolListId");

                    b.HasIndex("WasAmendmentDetected");

                    b.HasIndex("PartNumber", "Operation", "Revision")
                        .HasDatabaseName("IX_ToolingRecords_PartOpRev");

                    b.ToTable("ToolingRecords");
                });

            modelBuilder.Entity("ToolingExtractor.Core.Models.ToolingRecord", b =>
                {
                    b.HasOne("ToolingExtractor.Core.Models.ExtractionJob", null)
                        .WithMany("Records")
                        .HasForeignKey("ExtractionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ToolingExtractor.Core.Models.ExtractionJob", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
